push test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,7 +20,45 @@ jobs:
           node-version: "20"
 
       - name: Install dependencies
-        run: npm install
+        run: yarn install
+
+      - name: Install Playwright browsers
+        run: yarn playwright install
+        # This installs the required Playwright browsers
+
+      - name: Start Storybook
+        run: yarn storybook --ci --port 6006 &
+        # This command starts Storybook in the background
+
+      - name: Wait for Storybook to be available
+        run: npx wait-on http://127.0.0.1:6006
+
+      - name: Run tests with coverage
+        run: yarn test-storybook --coverage
+
+      - name: Check coverage threshold
+        run: |
+          COVERAGE=$(grep -o '"statements": [0-9.]*' ./coverage/coverage-summary.json | awk '{print $2}')
+          if (( $(echo "$COVERAGE < 50.0" |bc -l) )); then
+            echo "Test coverage ($COVERAGE%) is below the required threshold of 50%."
+            exit 1
+          else
+            echo "Test coverage ($COVERAGE%) meets the required threshold."
+          fi
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: ./coverage/lcov.info
+          flags: unittests
+          name: codecov-umbrella
+          fail_ci_if_error: true
+          verbose: true
+
+      - name: Stop Storybook
+        run: kill $(lsof -t -i:6006)
+        # This command stops the Storybook process
 
   deploy:
     runs-on: ubuntu-latest
@@ -31,14 +69,14 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install dependencies
-        run: npm install
+        run: yarn install
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+          aws-region: ap-southeast-1
 
       - name: Deploy to AWS with SST
         run: npx sst deploy --stage prod
